# import pandas as pd 
# import numpy as np 
# import matplotlib.pyplot as plt
# import seaborn as sns
# df = pd.read_csv(r"C:\Users\AdminOS\Desktop\python\sales_data.csv")
# df_clean = df.dropna(subset = ["Country"])
# print(df_clean.isnull().sum())
# print(df_clean.info())
# print(df_clean.head())
# print(df_clean.describe())
# print(df_clean.columns.to_list())
# print(df_clean['Category'].unique())
# print(df_clean["Unit Price"].describe().round(1))
# sns.boxplot(data =df_clean,x= "Unit Price",y = "Country")
# plt.show()
# print(df_clean.duplicated().sum())
# df_clean = df_clean.drop_duplicates()
# print(df_clean.dtypes)
# df_clean["Order Date"] = pd.to_datetime(df_clean["Order Date"])
# df_clean["Unit Price"] = df_clean["Unit Price"].astype(float)
# df_clean["Total Price"] = df_clean["Total Price"].astype(float)
# print(df_clean.dtypes)
# sales_by_country = df_clean.groupby("Country")["Total Price"].sum().sort_values(ascending=False)
# print(sales_by_country)
# sales_by_country.plot(kind="bar",title="sum of sales by country",ylabel="sum sales")
# plt.xticks(rotation = 45)
# plt.tight_layout()
# plt.show()
# top_products = df_clean.groupby("Product")["Total Price"].sum().sort_values(ascending=False)
# print(top_products)
# top_products.plot(kind="bar",title ="Total sales by each product",ylabel="Total sales")
# plt.xticks(rotation = 45)
# plt.tight_layout()
# plt.show()
# Sales_By_Category = df_clean.groupby("Category")["Total Price"].sum().sort_values(ascending= False)
# print(Sales_By_Category)
# Sales_By_Category.plot(kind="bar",title = "Sales by category", ylabel= "Total sales")
# plt.xticks(rotation = 45)
# plt.tight_layout()
# plt.show()
# df_clean["Month"] = df_clean["Order Date"].dt.to_period("M").astype(str)
# sales_by_month = df_clean.groupby("Month")["Total Price"].sum().sort_index()
# print(sales_by_month)
# sales_by_month.plot(kind="line", marker='o',title="Monthly Sales",ylabel="Total")
# plt.xticks(rotation = 45)
# plt.grid(True)
# plt.tight_layout()
# plt.show()
# sales_by_country = df_clean.groupby("Country")["Total Price"].sum().sort_values(ascending=False)
# print(sales_by_country)
# ax = sales_by_country.plot(kind="bar",title="Total Sales by country",ylabel="Total Sales",color= "g")
# plt.xticks(rotation = 45)
# plt.tight_layout()
# for i , v in enumerate(sales_by_country):
#     ax.text(i,v,f"{v:,.0f}",ha="center",va="bottom")
# plt.grid(True, axis='y', linestyle='--', alpha=0.7)
# plt.legend(loc= "upper right",fontsize = 9)
# plt.show()
# df_clean["Month"] = df_clean["Order Date"].dt.to_period("M").astype(str)
# sales = df_clean.groupby(["Month","Country"])["Total Price"].sum().reset_index()
# pivot_table = sales.pivot(index="Month",columns="Country",values="Total Price")
# pivot_table.plot(kind="line",marker = "o",figsize=(12,6))
# plt.title("Monthly Sales by Country")
# plt.ylabel("Total Sales")
# plt.xlabel("Month")
# plt.legend(title="Country",bbox_to_anchor=(1.05, 1),loc="upper left")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()
# print(df_clean[["Quantity","Total Price"]].describe())
# plt.figure(figsize=(8,5))
# plt.scatter(df_clean["Quantity"],df_clean["Total Price"],alpha = 0.5,color="teal")
# plt.title("Relationship between Quantity and Total Price")
# plt.xlabel("Quantity")
# plt.ylabel("Total Price")
# plt.grid(True,linestyle = "--",alpha= 0.5)
# plt.tight_layout()
# plt.show()










